### ISSUE TITLE
Problems in training GCN

### ISSUE THREAD

**Issue by zxpekko** [idea-iitd/GCOMB#18]
Hello, excuse me, I'm executing 'sh train_ script. sh', but there is a problem, according to the prompt, G should have no node object, but I did not get the modified training data. The following is an error prompt. I hope the author can answer it. Thank you very much.
===================================================================================
Training on Multiple Graphs ===========  0
sh ./example_supervised.sh ./real_data/large_kite/train/_bp
--train_prefix ./real_data/large_kite/train/_bp --model graphsage_meanpool --sigmoid
2022-11-13 12:24:15.002718: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Loading training data..
 num nodes  69578
 num nodes  69578
Done loading training data..
Traceback (most recent call last):
  File "/home/zhangxinping/.conda/envs/gcomb/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zhangxinping/.conda/envs/gcomb/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zhangxinping/GCOMB-master/MaxCover-20200616T101530Z-001/MaxCover/GraphSAGE-master/graphsage/supervised_train.py", line 387, in <module>
    tf.app.run()
  File "/home/zhangxinping/.conda/envs/gcomb/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/zhangxinping/.conda/envs/gcomb/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/zhangxinping/.conda/envs/gcomb/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/zhangxinping/GCOMB-master/MaxCover-20200616T101530Z-001/MaxCover/GraphSAGE-master/graphsage/supervised_train.py", line 384, in main
    train(train_data)
  File "/home/zhangxinping/GCOMB-master/MaxCover-20200616T101530Z-001/MaxCover/GraphSAGE-master/graphsage/supervised_train.py", line 168, in train
    context_pairs = context_pairs, mode="train", prefix=FLAGS.train_prefix)
  File "/home/zhangxinping/GCOMB-master/MaxCover-20200616T101530Z-001/MaxCover/GraphSAGE-master/graphsage/minibatch.py", line 213, in __init__
    self.adj, self.deg=self.construct_adj()
  File "/home/zhangxinping/GCOMB-master/MaxCover-20200616T101530Z-001/MaxCover/GraphSAGE-master/graphsage/minibatch.py", line 281, in construct_adj
    if self.G.node[nodeid]['test'] or self.G.node[nodeid]['val']:
AttributeError: 'Graph' object has no attribute 'node'

**Comment by sahilm1992** [comment]
Hi, 
I hope you are doing well.

I am unable to reproduce the error

Could you please check if the networkx version you are using is as per requirements(2,3) for both python2 and python3?

**Comment by sahilm1992** [comment]
Further, I saw your logs, it seems its python3.7 .  We had used python3.5.2 and python2.7.12.

Could you please try with them :) 
See details here :) 

https://github.com/idea-iitd/GCOMB

Thanks for your interest :)

**Comment by zxpekko** [comment]
Yes, I do use python 3.7. However, when I installed the python package of python 3.5, many packages indicated that they were not available under my Linux, so I used python 3.7. I changed the networkx version to the required version, but it still showed that G had no node object. No node and neighbors are found in the _ bp-G.json file, so an error is reported. So I don't know whether this has much to do with the version. But it is a problem that there is no object mentioned in the code in that file.

**Comment by sahilm1992** [comment]
It could be a network version issue it seems.

Other works have been able to use this code as baseline with the right set of packages[1,2].

Reference:
1. https://arxiv.org/pdf/2205.10106.pdf
2. https://raihanjoty.github.io/papers/li-et-al-piano-ieee-2022.pdf

At this moment, it seems to me that it could be something related to  networkx.  Since the members of networkx objects might be different for different versions.

Also Linux version could be a problem since these packages are a bit old now.

**Comment by zxpekko** [comment]
Yes, this problem has been solved. Thank you very much. However, in the prediction phase of GCN, it seems that the problem is dimension mismatch, but I did not modify the code or input data.
===================================================================================
Trained Model Loaded!
Predicting the classes of all the data set
Traceback (most recent call last):
  File "/home/zhangxinping/.conda/envs/gcomb/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/home/zhangxinping/.conda/envs/gcomb/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "/home/zhangxinping/.conda/envs/gcomb/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[50000] = 29540 is not in [0, 29540)
         [[{{node embedding_lookup_2}}]]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhangxinping/.conda/envs/gcomb/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zhangxinping/.conda/envs/gcomb/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zhangxinping/GCOMB-master/MaxCover-20200616T101530Z-001/MaxCover/GraphSAGE-master/graphsage/supervisedPredict.py", line 533, in <module>
    tf.app.run()
  File "/home/zhangxinping/.conda/envs/gcomb/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/zhangxinping/.conda/envs/gcomb/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/zhangxinping/.conda/envs/gcomb/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/zhangxinping/GCOMB-master/MaxCover-20200616T101530Z-001/MaxCover/GraphSAGE-master/graphsage/supervisedPredict.py", line 530, in main
    predict(train_data)
  File "/home/zhangxinping/GCOMB-master/MaxCover-20200616T101530Z-001/MaxCover/GraphSAGE-master/graphsage/supervisedPredict.py", line 349, in predict
    predict_prob, pred_classes, embeddings = incremental_predict(sess, model, minibatch, FLAGS.batch_size)
  File "/home/zhangxinping/GCOMB-master/MaxCover-20200616T101530Z-001/MaxCover/GraphSAGE-master/graphsage/supervisedPredict.py", line 116, in incremental_predict
    feed_dict=feed_dict_val)
  File "/home/zhangxinping/.conda/envs/gcomb/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 968, in run
    run_metadata_ptr)
  File "/home/zhangxinping/.conda/envs/gcomb/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/zhangxinping/.conda/envs/gcomb/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1369, in _do_run
    run_metadata)
  File "/home/zhangxinping/.conda/envs/gcomb/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[50000] = 29540 is not in [0, 29540)
         [[node embedding_lookup_2 (defined at /GCOMB-master/MaxCover-20200616T101530Z-001/MaxCover/GraphSAGE-master/graphsage/models.py:300) ]]

Errors may have originated from an input operation.
Input Source operations connected to node embedding_lookup_2:
 Variable (defined at /GCOMB-master/MaxCover-20200616T101530Z-001/MaxCover/GraphSAGE-master/graphsage/supervised_models.py:60)  
 Reshape_1 (defined at /GCOMB-master/MaxCover-20200616T101530Z-001/MaxCover/GraphSAGE-master/graphsage/models.py:274)

**Comment by sahilm1992** [comment]
Glad that worked :) 

Are you using CPU?
This problem occurs on CPU. Would request you to use GPU if that is the case.

**Comment by zxpekko** [comment]
Yes, I am considering running on GPU, but in addition, since I use version 2.4 of Tensorflow, the contrib package has been completely deleted, so please ask me about the original "from tensorflow.contrib import predictor" How to modify ? thank you very much.

**Comment by sahilm1992** [comment]
I do understand.
As of now I don't have expertise in the new version.
I will check once I get time.

Hope you understand :)

**Comment by zxpekko** [comment]
Ok,thank you very much,I will think further.Thanks again.

**Comment by zxpekko** [comment]
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[300] = 776564 is not in [0, 776564)
         [[node embedding_lookup_1 (defined at /.conda/envs/gcomb1/lib/python3.5/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
===========================================

Hello, when I run 'sh train_ script.sh' , this error occurs, but the program does not stop. After understanding, this is a problem of ' supervised_train .py'. Strangely, the program skipped the error report after a while, and then went to the RL program. Does this affect the final result? And would you please tell me how to solve this error? I did not find it on the Internet.

**Comment by sahilm1992** [comment]
This is possibly an issue when training without gpu .

Using a gpu should fix this error

**Comment by zxpekko** [comment]
Thanks for your reply. I will try to run it with GPU. Thanks again.

**Comment by sahilm1992** [comment]
Your welcome

**Comment by zxpekko** [comment]
I have an academic question. My direction is to use AI algorithm to solve combinatorial optimization problems. Your paper's methods of pruning noisy nodes and predicting good node scores and nsteps's Q-learning are very good. Where do these inspiration of ideas come from? And does the direction of graph optimization require high knowledge of graph theory? In other words, what knowledge is required for AI graph optimization algorithm? I would be grateful if you could answer my questions.

**Comment by sahilm1992** [comment]
Thanks for your interest.
you can drop me a mail on sahil.m1992@gmail.com. 
Will be happy to discuss :)

**Comment by zxpekko** [comment]
Thank you very much for your reply. I'm glad to discuss academic issues with you.It's my honor to discuss problems with predecessors
